---
- name: Allow IMAPS
  ufw:
    rule: allow
    name: "Dovecot Secure IMAP"
    delete: "{% if ufw_imaps_public %}no{% else %}yes{% endif %}"
  tags:
    - ufw
    - dovecot

- name: Allow IMAP
  ufw:
    rule: allow
    name: "Dovecot IMAP"
    delete: "{% if ufw_imap_public %}no{% else %}yes{% endif %}"
  tags:
    - ufw
    - dovecot
