---
- name: Ensure Domain directories exists
  file:
    path: /var/mail/vhosts/{{ item.domain }}
    state: directory
  with_items: "{{ mailuser }}"
  when: mailuser is defined
  tags:
    - mail
    - dovecot
    - vault

- name: Template users
  template:
    src: passwd.j2
    dest: /var/mail/vhosts/{{ item.domain }}/passwd
    owner: doveauth
    group: doveauth
    mode: 0700
  with_items: "{{ mailuser }}"
  when: mailuser is defined
  notify:
    - Reload dovecot
  tags:
    - mail
    - dovecot
    - vault

- name: Template shadow
  template:
    src: shadow.j2
    dest: /var/mail/vhosts/{{ item.domain }}/shadow
    owner: doveauth
    group: doveauth
    mode: 0700
  with_items: "{{ mailuser }}"
  when: mailuser is defined
  notify:
    - Reload dovecot
  tags:
    - mail
    - dovecot
    - vault

- name: create user folder
  file:
    path: /var/mail/vhosts/{{ item.0.domain }}/{{ item.1.username }}
    state: directory
    owner: "{{ item.1.UID }}"
    group: "{{ item.1.UID }}"
    mode: 0700
  with_subelements:
    - "{{ mailuser }}"
    - users
  when: mailuser is defined
  tags:
    - mail
    - dovecot
    - vault
